name: mega
services:
  mega:
    build:
      platforms:
        - linux/amd64
        - linux/arm64
      context: .
    environment:
      APP_NAME: "MeGa"
    ports:
      - "5800:5800"
    volumes:
      - "./mega_dir:/config"